// Keeps the whole app on the phone so it opens without internet.
const CACHE='stock-count-464aed6b50';
const FILES=["./", "index.html", "items.json", "xlsx.full.min.js", "zxing.min.js", "manifest.webmanifest", "icon-180.png", "icon-192.png", "icon-512.png", "img/a0.webp", "img/a1.webp", "img/a10.webp", "img/a100.webp", "img/a101.webp", "img/a102.webp", "img/a103.webp", "img/a104.webp", "img/a105.webp", "img/a106.webp", "img/a107.webp", "img/a11.webp", "img/a12.webp", "img/a13.webp", "img/a14.webp", "img/a15.webp", "img/a16.webp", "img/a17.webp", "img/a18.webp", "img/a19.webp", "img/a2.webp", "img/a20.webp", "img/a21.webp", "img/a22.webp", "img/a23.webp", "img/a24.webp", "img/a25.webp", "img/a26.webp", "img/a27.webp", "img/a28.webp", "img/a29.webp", "img/a3.webp", "img/a30.webp", "img/a31.webp", "img/a32.webp", "img/a33.webp", "img/a34.webp", "img/a35.webp", "img/a36.webp", "img/a37.webp", "img/a38.webp", "img/a39.webp", "img/a4.webp", "img/a40.webp", "img/a41.webp", "img/a42.webp", "img/a43.webp", "img/a44.webp", "img/a45.webp", "img/a46.webp", "img/a47.webp", "img/a48.webp", "img/a49.webp", "img/a5.webp", "img/a50.webp", "img/a51.webp", "img/a52.webp", "img/a53.webp", "img/a54.webp", "img/a55.webp", "img/a56.webp", "img/a57.webp", "img/a58.webp", "img/a59.webp", "img/a6.webp", "img/a60.webp", "img/a61.webp", "img/a62.webp", "img/a63.webp", "img/a64.webp", "img/a65.webp", "img/a66.webp", "img/a67.webp", "img/a68.webp", "img/a69.webp", "img/a7.webp", "img/a70.webp", "img/a71.webp", "img/a72.webp", "img/a73.webp", "img/a74.webp", "img/a75.webp", "img/a76.webp", "img/a77.webp", "img/a78.webp", "img/a79.webp", "img/a8.webp", "img/a80.webp", "img/a81.webp", "img/a82.webp", "img/a83.webp", "img/a84.webp", "img/a85.webp", "img/a86.webp", "img/a87.webp", "img/a88.webp", "img/a89.webp", "img/a9.webp", "img/a90.webp", "img/a91.webp", "img/a92.webp", "img/a93.webp", "img/a94.webp", "img/a95.webp", "img/a96.webp", "img/a97.webp", "img/a98.webp", "img/a99.webp"];
self.addEventListener('install',e=>{e.waitUntil(caches.open(CACHE).then(async c=>{for(let i=0;i<FILES.length;i+=12)await c.addAll(FILES.slice(i,i+12))}).then(()=>self.skipWaiting()))});
self.addEventListener('activate',e=>{e.waitUntil(caches.keys().then(ks=>Promise.all(ks.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim()))});
self.addEventListener('fetch',e=>{
  if(e.request.method!=='GET'||new URL(e.request.url).origin!==location.origin) return;
  e.respondWith(caches.match(e.request,{ignoreSearch:true}).then(r=>r||fetch(e.request)));
});
